### ISSUE TITLE
CVPR  2020 Oral Accepted Paper

### ISSUE THREAD

**Issue by AyanKumarBhunia** [MarkMoHR/Awesome-Sketch-Based-Applications#1]
Sketch Less for More: On-the-Fly Fine-Grained Sketch Based Image Retrieval
https://github.com/AyanKumarBhunia/on-the-fly-FGSBIR
https://arxiv.org/abs/2002.10310

**Comment by MarkMoHR** [comment]
Done! @AyanKumarBhunia
