### ISSUE TITLE
Two papers for [Sketch Based 3D Shape Modeling]

### ISSUE THREAD

**Issue by xchhuang** [MarkMoHR/Awesome-Sketch-Based-Applications#16]
Hi,

I find these two papers about volumetric shape modelling missing for **[5. Sketch Based 3D Shape Modeling]**:

1. [3D Sketching using Multi-View Deep Volumetric Prediction](https://www-sop.inria.fr/reves/Basilic/2018/DAIEB18/), ACM on Computer Graphics and Interactive Techniques 2018
2. [Deep Reconstruction of 3D Smoke Densities from Artist Sketches](http://www.byungsoo.me/project/sketch2density/), Eurographics 2022

Thanks.

**Comment by MarkMoHR** [comment]
Done. Thanks.
