### ISSUE TITLE
New Application [Learning Sketch Abstraction]

### ISSUE THREAD

**Issue by AyanKumarBhunia** [MarkMoHR/Awesome-Sketch-Based-Applications#2]
1. Learning Deep Sketch Abstraction, CVPR 2018. https://arxiv.org/abs/1804.04804 

2. Goal-Driven Sequential Data Abstraction, ICCV 2019. [http://openaccess.thecvf.com/content_ICCV_2019/papers/Muhammad_Goal-Driven_Sequential_Data_Abstraction_ICCV_2019_paper.pdf]

**Comment by MarkMoHR** [comment]
Added. Thanks!
