### ISSUE TITLE
Add ECCV 2018 paper

### ISSUE THREAD

**Issue by ashok-arjun** [MarkMoHR/Awesome-Sketch-Based-Applications#6]
Please add this to the list: [A Zero-Shot Framework for Sketch Based Image
Retrieval](https://openaccess.thecvf.com/content_ECCV_2018/papers/Sasikiran_Yelamarthi_A_Zero-Shot_Framework_ECCV_2018_paper.pdf)

**Comment by MarkMoHR** [comment]
@aiarjun Thanks! Would you please create a pull request?

**Comment by ashok-arjun** [comment]
Done! [PR]( https://github.com/MarkMoHR/Awesome-Sketch-Based-Applications/pull/7)
